//Invntus CAN Protocol
#include "defines.h"
#include <carloop.h>

#define INVNTS_TPDO1_ID 0x1B1
#define INVNTS_TPDO2_ID 0x2B1
#define INVNTS_TPDO3_ID 0x3B1
#define INVNTS_TPDO4_ID 0x4B1
#define INVNTS_TPDO5_ID 0x1C1
#define INVNTS_TPDO6_ID 0x2C1
#define INVNTS_SDO_RESP_ID 0x5B1

#define INVNTS_MUX_1 0x01
#define INVNTS_MUX_2 0x02
#define INVNTS_MUX_3 0x03

#define INVNTS_VOLTS_SUBINDEX 0x09
#define INVNTS_CURRENT_SUBINDEX 0x0A
#define INVNTS_AVG_CURRENT_SUBINDEX 0x0B
#define INVNTS_CHRG_STATUS_SUBINDEX 0x16
#define INVNTS_SN_SUBINDEX 0x1C

#define INVNTS_HEATER_STAT_INDEX 0x4810
#define INVNTS_HEATER_STATUS_SUBINDEX 0x00

#define INVNTS_MIN_CELL_TEMP_INDEX 0x4808
#define INVNTS_MIN_CELL_TEMP_SUBINDEX 0x00

#define INVNTS_MAX_CELL_TEMP_INDEX 0x4809
#define INVNTS_MAX_CELL_TEMP_SUBINDEX 0x00

#define INVNTS_INTERNAL_STAT_INDEX 0xD000
#define INVNTS_ATSAM_VER_SUBINDEX 0x20
#define INVNTS_BQ80_VER_SUBINDEX 0x23


typedef enum
{
  CT_INVNTS_VIRT_BATT_LOST_DELAY,
  NUM_INVNTS_VIRT_BATT_TIMERS,
  FIRST_INVNTS_VIRT_BATT_TIMER = 0
} INVNTS_VIRT_BATT_TIMERS;

void initInvntsVirtualBattCAN(void);
void recInvntsVirtualBattStatus(CANMessage message);
int InvntsVirtualBattCANok(void);
void InvntsVirtualBattSDOReadReq(int, int);
void InvntsVirtualBattSDOWriteReq(int, int);
